### ISSUE TITLE
Error: Authentication information is not present. Did you add credentials?

### ISSUE THREAD

**Issue by Cinezaster** [appbaseio/appbase-js#88]
V4.5.1 and V4.5.0, breaks my frontend and backend code.
Last working version 4.4.0
No code has been changed only update appbase-js version or did a npm update on latest version of @appbaseio/reactivesearch

_Error: Authentication information is not present. Did you add credentials?_

```
const appbaseDB = Appbase({
  url: <APPBASE_URL>,
  app: <APPBASE_APP>,
  credentials: <APPBASE_KEY>
})
```
Same on frontend:
```
<ReactiveBase
        app="APPBASE_APP"
        credentials="APPBASE_KEY">
```

**Comment by siddharthlatest** [comment]
@Cinezaster Can you share the exact error message for appbase-js? Is this a cluster connection or a hosted app connection?

**Update here:** This isn't a general issue with the client. Can you file a support issue from the dashboard? It may be specific to the BE version and we can check on this.

**Comment by Cinezaster** [comment]
@siddharthlatest 

This happens with @appbaseio/reactivesearch

```
Uncaught Error: url is required when using the elasticsearch Search backend.
    at appbase-js.es.js:190:1
    at Array.forEach (<anonymous>)
    at validateSchema (appbase-js.es.js:188:1)
    at new AppBase (appbase-js.es.js:301:1)
    at appbasejs (appbase-js.es.js:884:1)
    at ReactiveBase.setStore (ReactiveBase.js:221:1)
    at new ReactiveBase (ReactiveBase.js:67:1)
    at constructClassInstance (react-dom.development.js:12709:1)
    at updateClassComponent (react-dom.development.js:17425:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23620:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
```

If I add the url parameter with url: `https://scalr.api.appbase.io/`

I get the following error: (this is the same error I get in my node-js project )
```
appbase-js.es.js:318 Uncaught Error: Authentication information is not present. Did you add credentials?
    at new AppBase (appbase-js.es.js:318:1)
    at appbasejs (appbase-js.es.js:884:1)
    at ReactiveBase.setStore (ReactiveBase.js:221:1)
    at new ReactiveBase (ReactiveBase.js:67:1)
    at constructClassInstance (react-dom.development.js:12709:1)
    at updateClassComponent (react-dom.development.js:17425:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
    at workLoopSync (react-dom.development.js:22707:1)
    at renderRootSync (react-dom.development.js:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js:22293:1)
    at react-dom.development.js:11327:1
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js:11309:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23620:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at react-dom.development.js:23324:1
    at workLoop (scheduler.development.js:417:1)
    at flushWork (scheduler.development.js:390:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157:1)
```

**Comment by mohdashraf010897** [comment]
@Cinezaster We're able to replicate this issue, and it's related to a breakage of the hosted apps. Shall push a fix shortly. I would recommend considering migrating to the cluster's product instead of the apps.

Earlier reply: <s>Can you compare with the below-working app, it uses appbase-js@v4.5.1 https://codesandbox.io/embed/github/appbaseio-apps/emoji-search/tree/main/?fontsize=14&hidenavigation=1&theme=dark</s>
